[tools]
# For Mise to work properly
usage = "latest"
# Languages/Language tools
go = "latest"
node = "lts"
task = "latest"
tree-sitter = "latest"
uv = "latest"
# CLI Tools
bat = "latest"
"http:chafa" = { version = "1.18.1", url = "https://hpjansson.org/chafa/releases/static/chafa-1.18.1-1-x86_64-linux-gnu.tar.gz" }
direnv = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fnox = "latest"
fzf = "latest"
hk = "latest"
"pipx:httpie" = "latest"
opencode = "latest"
pkl = "latest"
ripgrep = "latest"
starship = "latest"
zoxide = "latest"

[settings]
experimental = true
