[tools]
# For Mise to work properly
usage = "latest"
# Languages/Language tools
node = "lts"
task = "latest"
tree-sitter = "latest"
uv = "latest"
# CLI Tools
bitwarden = "latest"
direnv = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fnox = "latest"
fzf = "latest"
hk = "latest"
"pipx:httpie" = "latest"
opencode = "latest"
pkl = "latest"
ripgrep = "latest"
starship = "latest"
zoxide = "latest"

[settings]
experimental = true
