[tools]
# For Mise
usage = "latest"
# Languages/Language tools
go = "latest"
node = "lts"
task = "latest"
tree-sitter = "latest"
uv = "latest"
# CLI Tools
direnv = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
"pipx:mistral-vibe" = "latest"
opencode = "latest"
ripgrep = "latest"
starship = "latest"
zoxide = "latest"

[settings]
experimental = true
